### PR TITLE
Added elmah.io

### PR DESCRIPTION
**Pull request by ThomasArdal**

### CODE REVIEW

**Comment by rdsubhas** [comment]
Hi @ThomasArdal thanks for the contribution, looks very interesting.

Quick question - Its tagged as open source, but is it OSS or commercial?

**Comment by ThomasArdal** [comment]
@rdsubhas It's both actually. All of our client libraries and some of the moving parts on elmah.io is open source here on GitHub. But the cloud service hosting users error messages is a commercial offering. Can I use both tags or should I switch to commercial, since one cannot use elmah.io without paying us for the hosting?

**Comment by ThomasArdal** [comment]
@rdsubhas Hi again. Should I change the tag to commercial or add two tags?

**Comment by rdsubhas** [comment]
@ThomasArdal sorry for the delay, yes can you pls change the tag to commercial, thanks :)

**Comment by ThomasArdal** [comment]
@rdsubhas No problem :smile: Done!

**Comment by rdsubhas** [comment]
Merged, thx!

**Pull request merged**
