### PR TITLE
Adding libcloud to Cloud-Paas

### PR DESCRIPTION
**Pull request by nmalbran**

### CODE REVIEW

**Comment by rdsubhas** [comment]
Hi @nmalbran thanks for the contrib! I think the CI build is failing for some other reason (its saying `bower-bourbon` package not found), am looking into it...

**Comment by nmalbran** [comment]
You're welcome :)
Yeah, I thought the same about the failed build.

**Comment by Cesarla** [comment]
@rdsubhas I'm facing the same error in my PR (https://github.com/devopsbookmarks/devopsbookmarks.com/pull/86)

**Comment by rdsubhas** [comment]
@Cesarla @nmalbran `bower-bourbon` was renamed to `bourbon`, am fixing it now...

**Comment by rdsubhas** [comment]
Latest CI build passed, so am merging. Thanks @nmalbran !

**Comment by nmalbran** [comment]
Great!

**Pull request merged**
