### PR TITLE
Add VAddy

### PR DESCRIPTION
**Pull request by ichikaway**

### CODE REVIEW

**Comment by scottmuc** [comment]
Very cool! Thanks for the contribution.

**Comment by ichikaway** [comment]
Thank you.
Could you merge this Pull Request?

**Comment by scottmuc** [comment]
Hehe, I thought I did, but I forgo to click the button twice to confirm :)

**Comment by ichikaway** [comment]
Thank you.
I'm proud that VAddy is on the list :)

**Pull request merged**
