### PR TITLE
Added the Assimilation System Management Suite.

### PR DESCRIPTION
**Pull request by Alan-R**
I added the category CMDB, which you don't yet have. It's really separate from the other categories. Although it's _related_ to configuration management, it's about providing an informational database for querying, not about pushing out configuration.

It's related to inventory management and so on. In my case, the database is all automatically maintained, and the orientation is less about inventory as it is about configuration - although we discover plenty of inventory-related stuff too.

One other use for it is to audit "what is" against what some other tool (ansible, chef, saltstack, puppet for example) says "what should be".

In addition, it can inform you via best practice audits of where things could be improved.

### CODE REVIEW

**Comment by scottmuc** [comment]
Perhaps "Auditing" could be an additional Topic in the website?

@rdsubhas, what do you think?

**Comment by Alan-R** [comment]
Auditing and compliance are both legitimate descriptions of what we do here. We provide a set of rules, which you can augment, change or replace.  Most of the best practices are security-related, but some are network-related. Others might be administration-related - like "you're running a service whose binary has been deleted - that's not best practice". Yes, I've had that happen to me - although in my case it mainly confused the monitoring software - it didn't know how to monitor "/usr/bin/java (deleted)" ;-). In the future, I may add this.

**Comment by rdsubhas** [comment]
@scottmuc @Alan-R sorry I couldn't respond earlier! My thoughts looking at the website:

> We help IT organizations manage and reduce complexity and transform security compliance from high drama to teachable moments.
> The Assimilation System Management Suite is centered around a CMDB (Configuration Management Data Base) which drives Monitoring, Cybersecurity and Network Management capabilities with near-zero configuration.

I believe tagging this as both Security and Monitoring will help users find this better as it fits with those two use-cases very well, rather than creating a separate category.

**Comment by Alan-R** [comment]
Are you waiting for something more from me? If so, let me know.  Thanks!

**Comment by scottmuc** [comment]
Apologies for the delay @Alan-R. Trying to get the maintenance of the project back to an acceptable level.

**Pull request merged**
