### PR TITLE
adding Solano CI

### PR DESCRIPTION
**Pull request by lumberg**

### CODE REVIEW

**Comment by scottmuc** [comment]
I tested the URL and it appears it doesn't work without the `www.` subdomain. Not sure which URL you intend to post.

**Comment by lumberg** [comment]
right - thank you, @scottmuc for catching that.  I've updated the URL and this should work.  :)

**Comment by scottmuc** [comment]
Cool, thanks for updating it.

**Comment by lumberg** [comment]
Thanks for the merge! Let me know if I can help in any way! :)

**Pull request merged**
