### PR TITLE
Added intelliment tool

### PR DESCRIPTION
**Pull request by efernandezleon**
Added Intelliment platform as a security devops tool.

### CODE REVIEW

**Comment by scottmuc** [comment]
@rdsubhas any ideas why we're not getting CI feedback on this?

@efernandezleon thank you for the contribution! Just need to take a look why the automated build didn't fire and provide us feedback.

**Comment by rdsubhas** [comment]
@scottmuc sorry I just checked this, will update by evening!

**Comment by rdsubhas** [comment]
@scottmuc can you try repairing github connectivity on snap?

screen shot 2016-07-01 at 13 51 03

**Comment by scottmuc** [comment]
@rdsubhas I didn't change anything. I resubmitted the delivery for the webhook and it kicked off SnapCI just fine. Must have been a reachability blip.

Build is good now. Merging! Thank you for your patience and contribution @efernandezleon!

**Comment by efernandezleon** [comment]
@scottmuc @rdsubhas Thank you guys for your work!

**Pull request merged**
