### PR TITLE
adding akeyless vault

### PR DESCRIPTION
**Pull request by yeshess**

### CODE REVIEW

**Review by scottmuc — APPROVED** [review]
Great to see more secret management stuff out there!

**Comment by yeshess** [comment]
Thanks, Scott! Although the site isn't working for me right now... when I choose a tag, everything is blank (tried on Incognito as well)....

**Comment by scottmuc** [comment]
Thanks for letting me know @yeshess. I'll take a look into it. With this whole archive of tools, we're actually not using any of them for this little website.

**Comment by scottmuc** [comment]
Heya @yeshess. The site should be good now. Looked like there was a trailing comma in this file. Not sure why CI didn't fail. Something to look at later. Thanks again for letting me know (and the contribution).

**Pull request merged**
