### PR TITLE
shutit

### PR DESCRIPTION
**Pull request by ianmiell**
Add ShutIt as a tool.

### CODE REVIEW

**Comment by rdsubhas** [comment]
Read about this in hacker news, very interesting and thanks!

**Comment by sriv** [comment]
Definitely looks cool, am going to play with it. Thanks @ianmeill

**Comment by ianmiell** [comment]
Great would love to hear your feedback, good or bad!

**Comment by scottmuc** [comment]
@ianmiell thanks for the contribution. This looks very interesting. Also, I'm really enjoyed your [Docker in the Enterprise](https://zwischenzugs.wordpress.com/2016/07/08/a-checklist-for-docker-in-the-enterprise/) blog post.

**Comment by ianmiell** [comment]
Hey Scott, that's great to hear! People don't get in touch enough :)
Ian

On Wed, Jul 13, 2016 at 5:14 PM, Scott Muc <notifications@github.com> wrote:

> @ianmiell <https://github.com/ianmiell> thanks for the contribution. This
> looks very interesting. Also, I'm really enjoyed your Docker in the
> Enterprise
> <https://zwischenzugs.wordpress.com/2016/07/08/a-checklist-for-docker-in-the-enterprise/>
> blog post.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/devopsbookmarks/devopsbookmarks.com/pull/133#issuecomment-232406323>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGrczYgHbXVr5WPFI9KgxG1Zb1WXJWFiks5qVQ8AgaJpZM4JLkKJ>
> .
>



-- 
My book on Docker in Practice: Get 39% off with the code 39miell
<http://manning.com/miell/?a_aid=zwischenzugs&a_bid=e0d48f62>

**Pull request merged**
