### PR TITLE
added datadog json to data tools

### PR DESCRIPTION
**Pull request by technovangelist**

### CODE REVIEW

**Comment by rdsubhas** [comment]
Looks cool, Thanks!

**Comment by irabinovitch** [comment]
@rdsubhas  Thanks for merging! I'm not seeing Datadog on the site yet.  Anything we need to do / change on this PR to make it visible?

**Comment by rdsubhas** [comment]
@irabinovitch checking this out...

**Comment by irabinovitch** [comment]
@rdsubhas Thanks let us know what you find.  Appreciate your help!

**Comment by rdsubhas** [comment]
@irabinovitch sorry took some time to fix this, done now :+1:

**Comment by irabinovitch** [comment]
Thanks!

**Pull request merged**
